"""initial_migration

Revision ID: d2461443a9c5
Revises: 25bacc564d93
Create Date: 2022-08-31 07:53:55.775712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2461443a9c5'
down_revision = '25bacc564d93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
